Repository DakaraProject/dakara-client-web, pull requests merged in 2018-05, with the labels that each got.

#80 Move playlist to its own page
  CHANGELOG.md
  src/jsx/components/Header.jsx
  src/jsx/components/generics/Navigator.jsx
  src/jsx/components/playlist/Entry.jsx
  src/jsx/components/playlist/List.jsx
  src/jsx/components/playlist/PlayedEntry.jsx
  src/jsx/components/playlist/PlayedList.jsx
  src/jsx/components/playlist/TabList.jsx
  src/jsx/components/playlistApp/PlaylistApp.jsx
  src/jsx/components/playlistApp/PlaylistInfoBar.jsx
  src/jsx/components/settings/TabList.jsx
  src/jsx/index.jsx
  src/jsx/reducers/playlist.js
  src/less/components/playlist_app/playlist.less
  src/less/components/playlist_app/playlist_app.less
  src/less/components/playlist_app/playlist_info_bar.less
Labels: enhancement, refactor

#83 Extend the research to all text fields in Song object
  src/jsx/components/library/song/Entry.jsx
  src/jsx/components/library/song/EntryExpanded.jsx
  src/jsx/components/song/Song.jsx
Labels: enhancement

#85 Make work link type name hard coded
  src/jsx/actions/playlist.js
  src/jsx/components/song/WorkLink.jsx
  src/jsx/reducers/library.js
  src/jsx/serverPropTypes/library.js
Labels: refactor
